import './Card.css';
import Heart from './Heart';
import Bookmark from './Bookmark';

function convert2Min(milliSec) {
    let total_sec = milliSec / 1000;
    let seconds = parseInt(total_sec % 60);
    let minutes = parseInt(total_sec / 60);
    return ` ${minutes}:${seconds} minutes`;
}

export default function Card({ song }) {
    // const song = SONG;
    return (
        <div className="card">

            <img
                src={song.album.images[1].url}
                alt={song.name}
                height={song.album.images[1].height}
                width={song.album.images[1].width}
            />
            <div className="info">
                <marquee>{song.name}</marquee>
                <ol>
                    {
                        ['popularity', 'type'].map((value, index) => {
                            return (
                                <li key={index}>
                                    <strong>{value} : </strong>
                                    <span>{song[value]}</span>
                                </li>
                            );
                        })
                    }
                    <li>
                        <strong>duration :</strong>
                        <span>{convert2Min(song.duration_ms)}</span>                    </li>
                    <li>
                        <strong>spotify link :</strong>
                        <a href={song.external_urls.spotify} target="_blank">spotify link</a>
                    </li>
                </ol>
            </div>
            <audio src={song.preview_url} controls></audio>
            <footer>
                <Heart song={song} />
                <Bookmark song={song} />
            </footer>
        </div>
    );
}




var SONG = {
    album: {
        album_type: "SINGLE",
        artists: [
            {
                external_urls: {
                    spotify: "https://open.spotify.com/artist/7s3J3Ie1oJNP08K0trggYB"
                },
                href: "https://api.spotify.com/v1/artists/7s3J3Ie1oJNP08K0trggYB",
                id: "7s3J3Ie1oJNP08K0trggYB",
                name: "TrigerPro",
                type: "artist",
                uri: "spotify:artist:7s3J3Ie1oJNP08K0trggYB"
            }
        ],
        available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
        ],
        external_urls: {
            spotify: "https://open.spotify.com/album/6n06NKFZkCeF7ERjX5c6jm"
        },
        href: "https://api.spotify.com/v1/albums/6n06NKFZkCeF7ERjX5c6jm",
        id: "6n06NKFZkCeF7ERjX5c6jm",
        images: [
            {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273ab86c3cceb2d7226b9cd8bc5",
                width: 640
            },
            {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02ab86c3cceb2d7226b9cd8bc5",
                width: 300
            },
            {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851ab86c3cceb2d7226b9cd8bc5",
                width: 64
            }
        ],
        name: "Senya - Itachi's Theme (From \"Naruto Shippuden\")",
        release_date: "2020-06-10",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:6n06NKFZkCeF7ERjX5c6jm"
    },
    artists: [
        {
            external_urls: {
                spotify: "https://open.spotify.com/artist/7s3J3Ie1oJNP08K0trggYB"
            },
            href: "https://api.spotify.com/v1/artists/7s3J3Ie1oJNP08K0trggYB",
            id: "7s3J3Ie1oJNP08K0trggYB",
            name: "TrigerPro",
            type: "artist",
            uri: "spotify:artist:7s3J3Ie1oJNP08K0trggYB"
        }
    ],
    available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "PR",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
    ],
    disc_number: 1,
    duration_ms: 91108,
    explicit: false,
    external_ids: {
        isrc: "QZGWW2116891"
    },
    external_urls: {
        spotify: "https://open.spotify.com/track/0Oto5hqPA0aQ5sKAY7pRmg"
    },
    href: "https://api.spotify.com/v1/tracks/0Oto5hqPA0aQ5sKAY7pRmg",
    id: "0Oto5hqPA0aQ5sKAY7pRmg",
    is_local: false,
    name: "Senya - Itachi's Theme (From \"Naruto Shippuden\")",
    popularity: 43,
    preview_url: "https://p.scdn.co/mp3-preview/fb31fce54ada0c96ce8b9e833b5f385b74fd5708?cid=cfe923b2d660439caf2b557b21f31221",
    track_number: 1,
    type: "track",
    uri: "spotify:track:0Oto5hqPA0aQ5sKAY7pRmg"
}